services:
    ricardonavarrom.vatin_validator:
        class: ricardonavarrom\VATINValidatorBundle\Validator\VATINValidator

    ricardonavarrom.vatin_validator.es:
        class: ricardonavarrom\VATINValidator\Validator\VATINValidatorES
        tags:
            - { name: ricardonavarrom.vatin_validator_located, locale: "es" }

    ricardonavarrom.vatin_validator_constraint.es:
        class: ricardonavarrom\VATINValidatorBundle\Validator\Constraints\VATINEsConstraintValidator
        arguments: ["@ricardonavarrom.vatin_validator.es"]
        tags:
            - { name: validator.constraint_validator }

    ricardonavarrom.vatin_validator.pt:
        class: ricardonavarrom\VATINValidator\Validator\VATINValidatorPT
        tags:
            - { name: ricardonavarrom.vatin_validator_located, locale: "pt" }

    ricardonavarrom.vatin_validator_constraint.pt:
        class: ricardonavarrom\VATINValidatorBundle\Validator\Constraints\VATINPtConstraintValidator
        arguments: ["@ricardonavarrom.vatin_validator.pt"]
        tags:
            - { name: validator.constraint_validator }
