services:
    ricardonavarrom.vatin_validator:
        class: ricardonavarrom\VATINValidatorBundle\Validator\VATINValidator

    ricardonavarrom.vatin_validator.es:
        class: ricardonavarrom\VATINValidatorBundle\Validator\VATINValidatorES
        tags:
            - { name: ricardonavarrom.vatin_validator_located, locale: "es" }

    ricardonavarrom.vatin_validator_constraint.es:
        class: ricardonavarrom\VATINValidatorBundle\Validator\Constraints\VATINEsConstraintValidator
        arguments: ["@ricardonavarrom.vatin_validator.es"]
        tags:
            - { name: validator.constraint_validator }