language: php

php:
    - 5.6

before_script:
    - composer self-update
    - composer install --dev --no-interaction

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls

notifications:
    on_success: never
    on_failure: always
    email: "ricardonavarromoral@gmail.com"
